### PR TITLE
Fix #185 make the jrxml path absolute

### LINKED ISSUE #185: Gradle: Report compile fails with Quarkus JasperReports Extension v1.0.3
Environment:
 * Windows 11
 * Eclipse Temurin 21
 * Gradle 8.12
 * Quarkus 3.17.7 with Kotlin
 * Quarkus JasperReports Extension v1.0.3

I have a very small test microservice with Quarkus+Kotlin+Gradle and just one JasperReports jrxml file. Wenn ich run "gradlew clean quarkusBuild" the build fails with the following error: 

Execution failed for task ':quarkusAppPartsBuild'.
> There was a failure while executing work items
   > A failure occurred while executing io.quarkus.gradle.tasks.worker.BuildWorker
      > io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        	[error]: Build step io.quarkiverse.jasperreports.deployment.JasperReportsProcessor#compileReports threw an exception: java.lang.NullPointerException: Cannot invoke "java.io.InputStream.read(byte[])" because "is" is null
        	at net.sf.jasperreports.engine.util.JRLoader.readBytes(JRLoader.java:370)
        	at net.sf.jasperreports.engine.util.JRLoader.loadBytes(JRLoader.java:348)
        	at net.sf.jasperreports.engine.xml.JRXmlLoader.loadXML(JRXmlLoader.java:160)
        	at net.sf.jasperreports.engine.xml.JRXmlLoader.load(JRXmlLoader.java:149)

When I execute "gradlew quarkusBuild" again (without changing anything) the build succeeds and the report is also compiled. When I change the version of the Quarkus JasperReports Extension to 1.0.2 the error is not reproducible. 

When I run my microservice in Intellij so that the report is compiled on app start the compile succeeds event with Quarkus JasperReports Extension v1.0.3. So there must be an issue in the Quarkus JasperReports Extension v1.0.3 concerning the Gradle Build.

### PR DESCRIPTION
**Pull request by bulldog98**
Fix #185

### CODE REVIEW

**Review by melloware — APPROVED** [review]

**Comment by melloware** [comment]
Build running now!

**Comment by melloware** [comment]
ahhh its failing the formatter!

**Comment by bulldog98** [comment]
formatted it now.

File: deployment/src/main/java/io/quarkiverse/jasperreports/deployment/JasperReportsProcessor.java [hunk 1]
```diff
@@ -3,10 +3,7 @@
 import static io.quarkus.deployment.pkg.PackageConfig.JarConfig.JarType.UBER_JAR;
 import static org.jboss.jandex.AnnotationTarget.Kind.CLASS;
 
-import java.io.ByteArrayOutputStream;
-import java.io.FileOutputStream;
-import java.io.IOException;
-import java.io.InputStream;
+import java.io.*;
```
Comment (nderwin) [inline deployment/src/main/java/io/quarkiverse/jasperreports/deployment/JasperReportsProcessor.java:6]: Can these be re-expanded, please?

**Comment by melloware** [comment]
Re-running

File: deployment/src/main/java/io/quarkiverse/jasperreports/deployment/JasperReportsProcessor.java (hunk 1 above)
Comment (bulldog98) [reply deployment/src/main/java/io/quarkiverse/jasperreports/deployment/JasperReportsProcessor.java:6]: That part was autoformatted by my Ide.

Comment (bulldog98) [reply deployment/src/main/java/io/quarkiverse/jasperreports/deployment/JasperReportsProcessor.java:6]: I'll update the PR, after I see the builds pass.

Comment (melloware) [reply deployment/src/main/java/io/quarkiverse/jasperreports/deployment/JasperReportsProcessor.java:6]: @bulldog98 if Ubuntu passes you are good.  Its MacOS that takes forever so if Ubuntu passes its good enough not to wait.

**Comment by melloware** [comment]
@all-contributors add @bulldog98 for code
